#include <iostream>
#include <string>
#include <vector>

using namespace std;



bool palindrome(string &str)
{
    string res = str;
    int i = 0;
    int j = str.size() - 1;
    while (i <= j)
    {
        swap(str[i], str[j]);
        i++;
        j--;
    }
    return (res == str) ? true : false;
}

// TLE Sol ->
bool validPalindrome(string s)
{
    string str = s;
    int i = 0;
    while (i < s.length())
    {
        str.erase(i, 1);
        if (palindrome(str))
        {
            return true;
        }
        str = s;
        i++;
    }
    return false;
}

int main()
{
    string s = "qzxpurfnltqaxujgtovibvlzaqljkkvuurfcwlfhhanjkzfezihnmhbexxegtgqbmxqydrgfacpgpherdkayhbbrvfrxnusrfvtnxcyxlhctdxuugtobbubjiinrrcefasxasatwvrdhrsudoytvaegxlwaffmhuhpmwpiqmgoqmyzamgippwokbdufnxvbpiymedcvmfifhdmboiohuzvdimhcydzrmauvkvgaoflpirkzynmvlemhojwmpiftvqmklempksaglllxfazclghrsprmqzfxconkmiqesozoyyqmhfnqhcnyrcqudumqphhllnjlnmjsszaaaoqeqsdcjmuntdzulacdtxrpqipnxggflsqhrnzjzceujzoejjllxuuhyxggenwmzfuikdlteykhbfjkucogtpumqrjyuabtdwfxtixunaiskqsdbvsdfbaslwkjactaygrjqvbjzimoinpjceqzqavukitrzsulesdpntbtrohljufbyaesbwaavjcslhdrityqevxufijpgzvgryqthjznafcrmfqujuyffaumjahhkjeqpjuwtapjelcwvkbasrbhizuwdxvndilbwgkzysdihrrkycjsktcnwunqrxluzohxlgfvmslgfahefgzbngkxsmggyxmsdujisyddbxxlvgjcvezpobhvuhakototeboscwlclkohwrimsbtyaenmnvkaljmkkptxsqjekqqkjhxdhafimtmkybzbetpcxwtnesyrrstxmwowzrlisogfyxacseiteubuptvtdskcaspokwdqsrdonntveszfeopjasgribpslgdkmofokexspsrxczhiummlckytunmmivrandqmqzgbmzdathueuoyhdprplxppsejunhsknazkkrebtpeavtwdxlrhptanvmtipuyauqjlnnhvocuicdbtxbwyurwfudbtqcbupqpyhtqfxazkfjrfirwopcxkwwaltipwfihmebhixtxmsxyeucvwdcirwmjwwkwrazldofhjdcxgulbewejlnasopkczgcampoiqrnjavhabipzoyjircowhukhkipqjgsosdjfgrkuiyxwnsbnhehimrpcwunmkdpnygodxwickgbnmotoqumgnfmoemhulsyoueluyrbijakfbyoywbnfhkqndbvooelywltqzkyrghwuvaghkwylfpmoylbqiwizuxubqkljbkiwgluznecsmsnutrkswaxacvrntmaeiarwjlbuwvrmlntoilzbpokstkrmnojicdcfqbrbhxqfpcnjojkusvflmcahuqgnbysoewgfxofaoqwrpzdqeyyfvwufcccwnqgxzsyrtzvmnqvmxwzrznrhobfperqclpwikxcktnnmcfswtkcxvplygmmaleeugmqyerwkkyfuybvlznuugplkburoqllundjyguxkoqevnnjdeedgqzdtsuawvvsemfmmeimpxbrmmmmvfojjuajjdwgyeoczzhdluugereqqfbnqkcuewjicbvvyvhozmpruprlheexcrumlflljjnbytbqfeijuwqoxhadojgjxltefmhngixprfazbtvfvnxlikvjomnqdjdagibkscpbpadrrlmrcmbpsynfqrczxpwuknraxbbudzcgusdeedwpntfdhvzuvvyysixdsayyrdigclzzadeypkfgixnwsezfubqbegoizgwvxnjxbkcrdszellbciqpztbzzdspwiueumnddpnpnqvibgkkwjnxjbxxjrksaudhqznyfqrcgxeysewbwitqtnvkfwdookttkhtppxbjckijrrhxuvxcttegfalwhzqwdpnsxyzqwundxrduuytvbcnabtzhjtuolukztuogvzktogbphktgxrqfbojuqmzankczhvtrjnwnparqywupkwtshzpocogjakgqoezegifyqunorlmqixmnsmdanmxugdmqxfovtgwbauahjjpftbgecjgeeldbjkffqmqmnycofjgkehyfjmydtmqwrlvvlyovfjjtdgjmvssfgzttvlthyqvkqtrqjsebygypdayahennqqerdfioibabtnmqmpebxogmctbmwshcafqjwxfjcsjnlpvcshyubykzvyobjnukpmzcawoakchjdfcfmjfplnzzxgzyerggkhpyytbbrnwhhcqdnrqrunjcqtrqyyjlgophjekpdnolhkfuhnjetwumgmunrzmuyjpofgfcduxhxwjnilmcidnpjruxhdbevddvixjawyhonpbekuaylodqbtzsopmhwwssycintsarsqtccnbkoxerxgmkedqdjspnxxrdvgpqylxfodhoygqvqwtznzjzsmfvbmruylzxbchjzzmacgriblzlzkszqptvplkemaugumcfnarsnollgylbkemewusthiegsorbljufmcoejekwgssozatkcqohtlixzliiywjxdicgbbpdyvpvglnnrpfrrxipuozjyxlsmxvosueyozfzpjmtlotekgwldttmslyqquviluosxnrcihwscjinbwqysuoqarojtrczdfsyhvglkmqxgokticlvjalgmldwhzxyydnxkgmhgfjnuytiumgjjxsvhubuaypkjlgepjycebuxgpqzqbooxakawbwxxqpmguqraoqcgwlnreclvmqhyvunijlsphtqfomzvjynsiypaijhjlnppjmcwplnwhxdrxlfjgerptjnhjhygszfslvtvdodayqadnahcrulqwijtccsiduczuxultmpnbctakulhrirjxfcnjuqlmvkcnezworhbpqzvwgosrzhjsqiuvpwcqocpstazkjebcismgkpjxobhknnaclizxscbbtdcpzpujdaqfxjbuqoyiqdumxxxtykojckamsiiucttuvmzhlrtnjebktsecfjblskgsaurjwhrusnfgsyeovxptoiizhqlvwromtcdulwfzbtikkqgzxseaftwgvmyjhvnnovwkkwkamjrksbhmpmjucbekewpzttcvjgwitgbkawmmotoumznfycsoesortmkvxqymewuyflewvtvlbuhdvtthemixlwnwddhknkufukqsywiebzyyypfelaboikwrmrtmhilvymkjbbznupuvzsizktlsfgxudmvjoctffffdrfxevwyqhuofsmkzadddqofnpqvqzedzpztdjmamfqcztbwvdjdanmztuodcyjzpwrfchctadwkvarzogvhlwjxkcelirycrxrpfkspbabcvzfmgasmtpkzydykmbsrcvagmibdruufoblrpjpxguvzzxnwlmkfxtzlbaxzbcbqdvieeusipvwstjhxxpghqumhfyzuvfcxssbbtxukogqnpyagyvwmmgaggoxjgazsmkaeoznhtyqphobdycaamqrjnlgrqxlsiuyshjfivgldriawacpraqxibtndzkszgffeddxwykybvxylbijtxtniwawjyzyuunzegebxbzaqojlgzteyluaseshhblfhhwdbwtqvufghyyxpoembxhrnmnqdndifjepbervrxnotcmouzjzwizvcfgljqmtthyjdystgwpmemnsawnvztgqkjawsbiksaqwffrzsatjzmfcfitgygpitumdqmhgzcyvontuctdcyyodcrocgvdgibjeqbmxwqmbvrugxqignittygbfcfdlgojqrjljofpdjydgodrbbvxciyhyojyihbveybnipxiggvsttnipzzglkwlhbtdpuymrneydmkgwrwikbhetjbbvbgzmlvdnhkpkekgraxlxreuapnqqofsmhhxmgxgwommdxklfgxxilkwventlzjtsxdjfowgzgrsdxocvbsdgifmofcszdfbtkyguaejwuzjrjjqmffnfsnyfggkqgoastkprrfkjhhzgdopmdtexuvupnwvejigmvbcfdljbqfpmkfirilpmjtoiuzitiaduqvabvabbagqyymdhtyqaoxhjaxmxapynvrmfkiwgkyzsiqqgwsdhnnavkkkmbitbwryppytdizvoishtzaoetnbiwalysbbprbvsvcsuonaxzsggfwiwznypggfycqlyyocymkqjiiyhesktubcgaksgvsfmibrxcsvkfrcvbkauhmyzqmebmqjteucsicykcnkjpdkztnazncrtomcjrdsphlrcuadviomxkbqmpemfqygtsuefbpypqbjzeekdeabqskuktlkdtmikvljpfovhubrupgxjjzafezqbyenkrkzbtibulqnnximtnwtfxpvgghwgzikqierujfjudontjeoelbxkctgscxkhvlbetteykextsvercalempnbcitvaavdfsnzjuqnihzwwjyquocdubpasljanlubrwknqnowbedksodtrsjcmdztflwinbstpgpurxafqsttwjakkrurutvycykrmtsyjwuwivgukocswevtinvmfxkfizfnxvvnkbwrjpridxcwchmlgkjkmsaxahdgasmrgzqiqdcqbrliyrisehbpgopzgcipqucwgkvccjtoefmoiwhbnejhohdlmmpgzaneckthoymmxoqoyavmrpjibtkwwyslttwkwjmsrdhuflsptzerjflwtbnvcfxrfeiwfvezbzuksguzlevqdnhjouoasdwnnpnildkdzobgwivgkipaktcgmnoxbsfjueggjfgrinegukyrvopkmwfnhcshxjwnxnnxbkwohodvrgdkdrahrdpqjrfgnyhqudpjaulfxrhipnnbutbbdmifmyuaiofnofhkxtpfrzhnbfymhojyxppoawfozjmcwotpfmwulikwafjbgmijrrpjagqpmkkfpsztrsjdqovykwnhgtaygicsaisjajroqbxujskubqlp"

    return 0
}